# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='atualizado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
