# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20170728_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
